### ISSUE TITLE
React Native Run Android no funciona

### ISSUE THREAD

**Issue by ghost** [HLSal/Curso-JS-React#1]
Luciano, estoy ejecutando el comando react-native run-android y no está funcionando.

**Comment by HLSal** [comment]
Hola esteban, probablemente no ejecutaste el comando "npm install". agradecería que me adjuntes detalles del error. Gracias!

**Comment by ghost** [comment]
Tenés razón Luciano. Era eso. Gracias.

**Comment by HLSal** [comment]
Me alegro @estebanmpa !
